<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNetter" Version="6.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ara3D.Geometry\Ara3D.Geometry.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.Logging\Ara3D.Logging.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.Studio.API\Ara3D.Studio.API.csproj" />
  </ItemGroup>

</Project>
