<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Geometry, model, math, and memory packages for Ara 3D SDK applications.</Description>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <PackageType>Dependency</PackageType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ara3D.Collections\Ara3D.Collections.csproj" />
    <ProjectReference Include="..\Ara3D.F8\Ara3D.F8.csproj" />
    <ProjectReference Include="..\Ara3D.Geometry\Ara3D.Geometry.csproj" />
    <ProjectReference Include="..\Ara3D.Memory\Ara3D.Memory.csproj" />
    <ProjectReference Include="..\Ara3D.Models\Ara3D.Models.csproj" />
  </ItemGroup>
</Project>
