// Autogenerated file: DO NOT EDIT
// Created on 2025-06-03 11:05:01 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Plato
{
    [StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Number: IRealNumber<Number>
    {
        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Number Create() => new Number();

        // Static default implementation
        public static readonly Number Default = default;

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Number other) => Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Number other) => !Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Number other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(Number a, Number b) => a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(Number a, Number b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Value.GetHashCode();
        [MethodImpl(AggressiveInlining)] public override string ToString() => Value.ToString();

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public Integer NumComponents { [MethodImpl(AggressiveInlining)] get => 1; }
        public System.Collections.Generic.IReadOnlyList<Number> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Number>(Value); }
        [MethodImpl(AggressiveInlining)] public static Number CreateFromComponents(System.Collections.Generic.IReadOnlyList<Number> numbers) => new Number(numbers[0]);

        [MethodImpl(AggressiveInlining)] public static Number CreateFromComponent(Number x) => new Number(x);

        // Implemented interface functions
        public Angle Turns { [MethodImpl(AggressiveInlining)] get  => this.Multiply(Constants.TwoPi); } 
public Angle Degrees { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)360)).Turns; } 
public Angle Gradians { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)400)).Turns; } 
public Angle ArcMinutes { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)60)).Degrees; } 
public Angle ArcSeconds { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)60)).ArcMinutes; } 
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.AlmostEqual(x: Number,y: Number): Boolean [Library]; */
        /* Core_7.AlmostEqual(x: IVectorLike,y: IVectorLike): Boolean [Library]; */
        [MethodImpl(AggressiveInlining)] public Boolean AlmostEqual(Number y) => this.Subtract(y).Abs.LessThanOrEquals(this.MultiplyEpsilon(y));
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.AlmostZero(x: Number): Boolean [Library]; */
        /* Core_7.AlmostZero(x: IVectorLike): Boolean [Library]; */
        public Boolean AlmostZero { [MethodImpl(AggressiveInlining)] get  => this.Abs.LessThan(Constants.Epsilon); } 
public Boolean AlmostZeroOrOne { [MethodImpl(AggressiveInlining)] get  => this.AlmostEqual(Zero).Or(this.AlmostEqual(One)); } 
// AMBIGUOUS FUNCTIONS 3
        /* Core_7.Average(x: Number,y: Number): Number [Library]; */
        /* Core_7.Average(x: IVectorLike,y: IVectorLike): IVectorLike [Library]; */
        /* Core_7.Average(a: IInterpolatable,b: IInterpolatable): IInterpolatable [Library]; */
        [MethodImpl(AggressiveInlining)] public Number Average(Number y) => this.Add(y).Half;
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.Between(x: Number,a: Number,b: Number): Boolean [Library]; */
        /* Core_7.Between(x: IVectorLike,a: IVectorLike,b: IVectorLike): Boolean [Library]; */
        [MethodImpl(AggressiveInlining)] public Boolean Between(Number a, Number b) => this.GreaterThanOrEquals(a).And(this.LessThanOrEquals(b));
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.Between01(x: Number): Boolean [Library]; */
        /* Core_7.Between01(x: IVectorLike): Boolean [Library]; */
        public Boolean Between01 { [MethodImpl(AggressiveInlining)] get  => this.Between(((Number)0), ((Number)1)); } 
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.ClampZeroOne(x: Number): Number [Library]; */
        /* Core_7.ClampZeroOne(x: IVectorLike): IVectorLike [Library]; */
        public Number ClampZeroOne { [MethodImpl(AggressiveInlining)] get  => this.Clamp(Zero, One); } 
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.Fract(x: Number): Number [Library]; */
        /* Core_7.Fract(x: IVectorLike): IVectorLike [Library]; */
        public Number Fract { [MethodImpl(AggressiveInlining)] get  => this.Subtract(this.Floor); } 
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.FromOne(x: Number): Number [Library]; */
        /* Core_7.FromOne(x: IVectorLike): IVectorLike [Library]; */
        public Number FromOne { [MethodImpl(AggressiveInlining)] get  => ((Number)1).Subtract(this); } 
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.InversePow(x: Number,y: Number): Number [Library]; */
        /* Core_7.InversePow(x: IVectorLike,y: IVectorLike): IVectorLike [Library]; */
        [MethodImpl(AggressiveInlining)] public Number InversePow(Number y) => this.Pow(y.Reciprocal);
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.Lerp(a: Number,b: Number,t: Number): Number [Library]; */
        /* Core_7.Lerp(a: IVectorLike,b: IVectorLike,t: Number): IVectorLike [Library]; */
        [MethodImpl(AggressiveInlining)] public Number Lerp(Number b, Number t) => this.Multiply(t.FromOne).Add(b.Multiply(t));
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.MultiplyEpsilon(x: Number,y: Number): Number [Library]; */
        /* Core_7.MultiplyEpsilon(x: IVectorLike,y: IVectorLike): IVectorLike [Library]; */
        [MethodImpl(AggressiveInlining)] public Number MultiplyEpsilon(Number y) => this.Abs.Greater(y.Abs).Multiply(Constants.Epsilon);
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.Pow2(x: Number): Number [Library]; */
        /* Core_7.Pow2(x: IVectorLike): IVectorLike [Library]; */
        public Number Pow2 { [MethodImpl(AggressiveInlining)] get  => this.Multiply(this); } 
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.Pow3(x: Number): Number [Library]; */
        /* Core_7.Pow3(x: IVectorLike): IVectorLike [Library]; */
        public Number Pow3 { [MethodImpl(AggressiveInlining)] get  => this.Multiply(this.Multiply(this)); } 
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.Pow4(x: Number): Number [Library]; */
        /* Core_7.Pow4(x: IVectorLike): IVectorLike [Library]; */
        public Number Pow4 { [MethodImpl(AggressiveInlining)] get  => this.Multiply(this.Multiply(this.Multiply(this))); } 
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.Pow5(x: Number): Number [Library]; */
        /* Core_7.Pow5(x: IVectorLike): IVectorLike [Library]; */
        public Number Pow5 { [MethodImpl(AggressiveInlining)] get  => this.Multiply(this.Multiply(this.Multiply(this.Multiply(this)))); } 
// AMBIGUOUS FUNCTIONS 2
        /* Core_7.Sqr(x: Number): Number [Library]; */
        /* Core_7.Sqr(x: IVectorLike): IVectorLike [Library]; */
        public Number Sqr { [MethodImpl(AggressiveInlining)] get  => this.Pow2; } 
[MethodImpl(AggressiveInlining)] public _T0 Multiply<_T0>(_T0 x) where _T0 : IScalarArithmetic<_T0> => x.Multiply(this);
[MethodImpl(AggressiveInlining)] public Number SineWave(Number amplitude, Number frequency, Number phase) => amplitude.Multiply(frequency.Multiply(this.Turns.Sin).Add(phase));
[MethodImpl(AggressiveInlining)] public Number StaircaseFloor(Integer steps) => this.Multiply(steps).Floor.Divide(steps);
[MethodImpl(AggressiveInlining)] public Number StaircaseCeiling(Integer steps) => this.Multiply(steps).Ceiling.Divide(steps);
[MethodImpl(AggressiveInlining)] public Number StaircaseRound(Integer steps) => this.Multiply(steps).Round(((Integer)0)).Divide(steps);
[MethodImpl(AggressiveInlining)] public Point2D Spiral(Number R, Number r, Number numTurns) => new Vector2(this.Turns.Multiply(numTurns).Cos, this.Turns.Multiply(numTurns).Sin).Multiply(r.Lerp(R, this));
[MethodImpl(AggressiveInlining)] public Matrix4x4 Multiply(Matrix4x4 value1) => this * value1;
        [MethodImpl(AggressiveInlining)] public Matrix3x2 Multiply(Matrix3x2 value1) => this * value1;
        [MethodImpl(AggressiveInlining)] public Vector2 Multiply(Vector2 right) => this * right;
        [MethodImpl(AggressiveInlining)] public Vector3 Multiply(Vector3 right) => this * right;
        [MethodImpl(AggressiveInlining)] public Vector4 Multiply(Vector4 right) => this * right;
        [MethodImpl(AggressiveInlining)] public Vector8 Multiply(Vector8 right) => this * right;
        [MethodImpl(AggressiveInlining)] public Vector8 Divide(Vector8 right) => this / right;
        [MethodImpl(AggressiveInlining)] public Number Add(Number b) => this + b;
        [MethodImpl(AggressiveInlining)] public Number Subtract(Number b) => this - b;
        [MethodImpl(AggressiveInlining)] public Number Multiply(Number b) => this * b;
        [MethodImpl(AggressiveInlining)] public Number Divide(Number b) => this / b;
        public Number Negative { [MethodImpl(AggressiveInlining)] get => -this; }
        [MethodImpl(AggressiveInlining)] public Boolean LessThan(Number b) => this < b;
        [MethodImpl(AggressiveInlining)] public Boolean LessThanOrEquals(Number b) => this <= b;
        [MethodImpl(AggressiveInlining)] public Boolean GreaterThan(Number b) => this > b;
        [MethodImpl(AggressiveInlining)] public Boolean GreaterThanOrEquals(Number b) => this >= b;
        [MethodImpl(AggressiveInlining)] public Angle Multiply(Angle a) => this * a;
        public Translation3D TranslationX { [MethodImpl(AggressiveInlining)] get  => this.XVector3; } 
public Translation3D TranslationY { [MethodImpl(AggressiveInlining)] get  => this.YVector3; } 
public Translation3D TranslationZ { [MethodImpl(AggressiveInlining)] get  => this.ZVector3; } 
public Scaling3D UniformScaling3D { [MethodImpl(AggressiveInlining)] get  => new Vector3(this); } 
public Vector2 Vector2 { [MethodImpl(AggressiveInlining)] get  => (this, this); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Vector2(Number s) => s.Vector2;
        public Vector2 XVector2 { [MethodImpl(AggressiveInlining)] get  => (this, ((Number)0)); } 
public Vector2 YVector2 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), this); } 
public Vector3 Vector3 { [MethodImpl(AggressiveInlining)] get  => (this, this, this); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Vector3(Number s) => s.Vector3;
        public Vector3 XVector3 { [MethodImpl(AggressiveInlining)] get  => (this, ((Number)0), ((Number)0)); } 
public Vector3 YVector3 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), this, ((Number)0)); } 
public Vector3 ZVector3 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)0), this); } 
public Vector4 Vector4 { [MethodImpl(AggressiveInlining)] get  => (this, this, this, this); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Vector4(Number s) => s.Vector4;
        public Vector4 XVector4 { [MethodImpl(AggressiveInlining)] get  => (this, ((Number)0), ((Number)0), ((Number)0)); } 
public Vector4 YVector4 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), this, ((Number)0), ((Number)0)); } 
public Vector4 ZVector4 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)0), this, ((Number)0)); } 
public Vector4 WVector4 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)0), ((Number)0), this); } 
public Vector8 Vector8 { [MethodImpl(AggressiveInlining)] get  => (this, this, this, this, this, this, this, this); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Vector8(Number s) => s.Vector8;
        [MethodImpl(AggressiveInlining)] public Number Barycentric(Number v2, Number v3, Vector2 uv) => this.Add(v2.Subtract(this)).Multiply(uv.X).Add(v3.Subtract(this).Multiply(uv.Y));
[MethodImpl(AggressiveInlining)] public Number Linear(Number b, Number x) => this.Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)] public Number Quadratic(Number b, Number c, Number x) => this.Multiply(x.Sqr).Add(b.Multiply(x).Add(c));
[MethodImpl(AggressiveInlining)] public Number Cubic(Number b, Number c, Number d, Number x) => this.Multiply(x.Pow3).Add(b.Multiply(x.Sqr).Add(c.Multiply(x).Add(d)));
[MethodImpl(AggressiveInlining)] public Number Quartic(Number b, Number c, Number d, Number e, Number x) => this.Multiply(x.Pow4).Add(b.Multiply(x.Pow3).Add(c.Multiply(x.Sqr).Add(d.Multiply(x).Add(e))));
[MethodImpl(AggressiveInlining)] public Number LinearDerivative(Number b, Number x) => this;
[MethodImpl(AggressiveInlining)] public Number LinearSecondDerivative(Number b, Number x) => default;
[MethodImpl(AggressiveInlining)] public Number QuadraticDerivative(Number b, Number c, Number x) => this.Multiply(((Number)2)).Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)] public Number QuadraticSecondDerivative(Number b, Number c, Number x) => this.Multiply(((Number)2));
[MethodImpl(AggressiveInlining)] public Number CubicDerivative(Number b, Number c, Number d, Number x) => this.Multiply(((Number)3)).Multiply(x.Sqr).Add(b.Multiply(((Number)2)).Multiply(x).Add(c));
[MethodImpl(AggressiveInlining)] public Number CubicSecondDerivative(Number b, Number c, Number d, Number x) => this.Multiply(((Number)6)).Multiply(x).Add(b.Multiply(((Number)2)));
[MethodImpl(AggressiveInlining)] public Number QuarticDerivative(Number b, Number c, Number d, Number e, Number x) => this.Multiply(((Number)4)).Multiply(x.Pow3).Add(b.Multiply(((Number)3)).Multiply(x.Sqr).Add(c.Multiply(((Number)2)).Multiply(x).Add(d)));
[MethodImpl(AggressiveInlining)] public Number QuarticSecondDerivative(Number b, Number c, Number d, Number e, Number x) => this.Multiply(((Number)12)).Multiply(x.Sqr).Add(b.Multiply(((Number)6)).Multiply(x).Add(c.Multiply(((Number)2))));
[MethodImpl(AggressiveInlining)] public Number CubicBezier(Number b, Number c, Number d, Number t) => this.Multiply(((Number)1).Subtract(t).Pow3).Add(b.Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Sqr.Multiply(t))).Add(c.Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Multiply(t.Sqr))).Add(d.Multiply(t.Pow3))));
[MethodImpl(AggressiveInlining)] public Number CubicBezierDerivative(Number b, Number c, Number d, Number t) => b.Subtract(this).Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Sqr)).Add(c.Subtract(b).Multiply(((Number)6).Multiply(((Number)1).Subtract(t).Multiply(t))).Add(d.Subtract(c).Multiply(((Number)3).Multiply(t.Sqr))));
[MethodImpl(AggressiveInlining)] public Number CubicBezierSecondDerivative(Number b, Number c, Number d, Number t) => c.Subtract(b.Multiply(((Number)2)).Add(this)).Multiply(((Number)6).Multiply(((Number)1).Subtract(t))).Add(d.Subtract(c.Multiply(((Number)2)).Add(b)).Multiply(((Number)6).Multiply(t)));
[MethodImpl(AggressiveInlining)] public Number QuadraticBezier(Number b, Number c, Number t) => this.Multiply(((Number)1).Subtract(t).Sqr).Add(b.Multiply(((Number)2).Multiply(((Number)1).Subtract(t).Multiply(t))).Add(c.Multiply(t.Sqr)));
[MethodImpl(AggressiveInlining)] public Number QuadraticBezierDerivative(Number b, Number c, Number t) => b.Subtract(this).Multiply(((Number)2).Multiply(((Number)1).Subtract(t))).Add(c.Subtract(b).Multiply(((Number)2).Multiply(t)));
[MethodImpl(AggressiveInlining)] public Number QuadraticBezierSecondDerivative(Number b, Number c, Number t) => ((Number)2).Multiply(this.Subtract(b.Multiply(((Number)2)).Add(c)));
[MethodImpl(AggressiveInlining)] public Number Hermite(Number p1, Number m0, Number m1, Number t) => this.Multiply(((Number)2).Multiply(t.Pow3).Subtract(((Number)3).Multiply(t.Sqr).Add(((Number)1)))).Add(m0.Multiply(t.Pow3.Subtract(((Number)2).Multiply(t.Sqr).Add(t))).Add(p1.Multiply(((Number)2).Multiply(t.Pow3).Add(((Number)3).Multiply(t.Sqr)).Negative).Add(m1.Multiply(t.Pow3.Subtract(t.Sqr)))));
[MethodImpl(AggressiveInlining)] public Number HermiteDerivative(Number p1, Number m0, Number m1, Number t) => this.Multiply(((Number)6).Multiply(t.Sqr).Subtract(((Number)6).Multiply(t))).Add(m0.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)4).Multiply(t).Add(((Number)1)))).Add(p1.Multiply(((Number)6).Multiply(t.Sqr).Add(((Number)6).Multiply(t)).Negative).Add(m1.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)2).Multiply(t))))));
[MethodImpl(AggressiveInlining)] public Number CatmullRom(Number p1, Number p2, Number p3, Number t) => ((Number)0.5).Multiply(p1.Multiply(((Number)2)).Add(p2.Subtract(this).Multiply(t).Add(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5)).Add(p2.Multiply(((Number)4)).Subtract(p3))).Multiply(t.Sqr).Add(this.Add(p1.Multiply(((Number)3)).Subtract(p2.Multiply(((Number)3)).Add(p3))).Negative.Multiply(t.Pow3)))));
[MethodImpl(AggressiveInlining)] public Number CatmullRomDerivative(Number p1, Number p2, Number p3, Number t) => ((Number)0.5).Multiply(p2.Subtract(this).Add(((Number)2).Multiply(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5)).Add(p2.Multiply(((Number)4)).Subtract(p3))).Multiply(t)).Add(((Number)3).Multiply(this.Add(p1.Multiply(((Number)3)).Subtract(p2.Multiply(((Number)3)).Add(p3))).Negative.Multiply(t.Sqr)))));
public Number SmoothStep { [MethodImpl(AggressiveInlining)] get  => this.Sqr.Multiply(this.Twice.Add(((Number)3)).Negative); } 
public Number SmootherStep { [MethodImpl(AggressiveInlining)] get  => this.Pow3.Multiply(this.Multiply(((Number)6)).Subtract(((Number)15))).Add(((Number)10)); } 
public static Number Zero { [MethodImpl(AggressiveInlining)] get  => Number.CreateFromComponent(((Number)0)); } 
public static Number One { [MethodImpl(AggressiveInlining)] get  => Number.CreateFromComponent(((Number)1)); } 
public static Number MinValue { [MethodImpl(AggressiveInlining)] get  => Number.CreateFromComponent(Plato.Number.MinValue); } 
public static Number MaxValue { [MethodImpl(AggressiveInlining)] get  => Number.CreateFromComponent(Plato.Number.MaxValue); } 
[MethodImpl(AggressiveInlining)] public Number Reduce(Number initial, System.Func<Number, Number, Number> f) => this.Components.Reduce(initial, f);
public Number MinComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this[((Integer)0)], (a, b)  => a.Min(b)); } 
public Number MaxComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this[((Integer)0)], (a, b)  => a.Max(b)); } 
public Number SumComponents { [MethodImpl(AggressiveInlining)] get  => this.Reduce(((Number)0), (a, b)  => a.Add(b)); } 
public Number SumSqrComponents { [MethodImpl(AggressiveInlining)] get  => this.Reduce(((Number)0), (a, b)  => a.Add(b.Multiply(b))); } 
public Number AvgComponent { [MethodImpl(AggressiveInlining)] get  => this.SumComponents.Divide(this.NumComponents); } 
public Number Magnitude { [MethodImpl(AggressiveInlining)] get  => this.MagnitudeSquared.Sqrt; } 
public Number MagnitudeSquared { [MethodImpl(AggressiveInlining)] get  => this.SumSqrComponents.Divide(this.NumComponents); } 
public Number ReciprocalSquareRootEstimate { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ReciprocalSquareRootEstimate); } 
[MethodImpl(AggressiveInlining)] public System.Collections.Generic.IReadOnlyList<Number> Sample(Number b, Integer n){
            var _var133 = b;
            {
                var _var132 = this;
                return n.LinearSpace.Map((i)  => _var132.Lerp(_var133, i));
            }
        }

public Number Half { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)2)); } 
public Number Quarter { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)4)); } 
public Number Eight { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)8)); } 
public Number Sixteenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)16)); } 
public Number Tenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)10)); } 
public Number Twice { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)2)); } 
public Number Hundred { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)100)); } 
public Number Thousand { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)1000)); } 
public Number Million { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Thousand; } 
public Number Billion { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Million; } 
public Number Hundredth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)100)); } 
public Number Thousandth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)1000)); } 
public Number Millionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Thousandth; } 
public Number Billionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Millionth; } 
[MethodImpl(AggressiveInlining)] public Number At(Integer n) => this.Components[n];
public Number this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }
        [MethodImpl(AggressiveInlining)] public Number MapComponents(System.Func<Number, Number> f) => Number.CreateFromComponents(this.Components.Map(f));
[MethodImpl(AggressiveInlining)] public Number ZipComponents(Number b, System.Func<Number, Number, Number> f) => Number.CreateFromComponents(this.Components.Zip(b.Components, f));
[MethodImpl(AggressiveInlining)] public Number ZipComponents(Number b, Number c, System.Func<Number, Number, Number, Number> f) => Number.CreateFromComponents(this.Components.Zip(b.Components, c.Components, f));
[MethodImpl(AggressiveInlining)] public Boolean AllZipComponents(Number b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AllZipComponents(Number b, Number c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AnyZipComponents(Number b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AnyZipComponents(Number b, Number c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AllComponents(System.Func<Number, Boolean> predicate) => this.Components.All(predicate);
[MethodImpl(AggressiveInlining)] public Boolean AnyComponent(System.Func<Number, Boolean> predicate) => this.Components.Any(predicate);
[MethodImpl(AggressiveInlining)] public Number Lesser(Number b) => this.LessThanOrEquals(b) ? this : b;
[MethodImpl(AggressiveInlining)] public Number Greater(Number b) => this.GreaterThanOrEquals(b) ? this : b;

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Number Modulo(Number b) => this % b;
    }
    // Extension methods for the type
    public static partial class Extensions
    {
        [MethodImpl(AggressiveInlining)] public static Number Modulo(this Number a, Number b) => a.Modulo(b);
        [MethodImpl(AggressiveInlining)] public static Number Modulo(this float a, Number b) => ((Number)a).Modulo(b);
        [MethodImpl(AggressiveInlining)] public static Angle Turns(this float x) => ((Number)x).Turns;
        [MethodImpl(AggressiveInlining)] public static Angle Degrees(this float x) => ((Number)x).Degrees;
        [MethodImpl(AggressiveInlining)] public static Angle Gradians(this float x) => ((Number)x).Gradians;
        [MethodImpl(AggressiveInlining)] public static Angle ArcMinutes(this float x) => ((Number)x).ArcMinutes;
        [MethodImpl(AggressiveInlining)] public static Angle ArcSeconds(this float x) => ((Number)x).ArcSeconds;
        [MethodImpl(AggressiveInlining)] public static Boolean AlmostEqual(this float x, Number y) => ((Number)x).AlmostEqual(y);
        [MethodImpl(AggressiveInlining)] public static Boolean AlmostZero(this float x) => ((Number)x).AlmostZero;
        [MethodImpl(AggressiveInlining)] public static Boolean AlmostZeroOrOne(this float x) => ((Number)x).AlmostZeroOrOne;
        [MethodImpl(AggressiveInlining)] public static Number Average(this float x, Number y) => ((Number)x).Average(y);
        [MethodImpl(AggressiveInlining)] public static Boolean Between(this float x, Number a, Number b) => ((Number)x).Between(a, b);
        [MethodImpl(AggressiveInlining)] public static Boolean Between01(this float x) => ((Number)x).Between01;
        [MethodImpl(AggressiveInlining)] public static Number ClampZeroOne(this float x) => ((Number)x).ClampZeroOne;
        [MethodImpl(AggressiveInlining)] public static Number Fract(this float x) => ((Number)x).Fract;
        [MethodImpl(AggressiveInlining)] public static Number FromOne(this float x) => ((Number)x).FromOne;
        [MethodImpl(AggressiveInlining)] public static Number InversePow(this float x, Number y) => ((Number)x).InversePow(y);
        [MethodImpl(AggressiveInlining)] public static Number Lerp(this float a, Number b, Number t) => ((Number)a).Lerp(b, t);
        [MethodImpl(AggressiveInlining)] public static Number MultiplyEpsilon(this float x, Number y) => ((Number)x).MultiplyEpsilon(y);
        [MethodImpl(AggressiveInlining)] public static Number Pow2(this float x) => ((Number)x).Pow2;
        [MethodImpl(AggressiveInlining)] public static Number Pow3(this float x) => ((Number)x).Pow3;
        [MethodImpl(AggressiveInlining)] public static Number Pow4(this float x) => ((Number)x).Pow4;
        [MethodImpl(AggressiveInlining)] public static Number Pow5(this float x) => ((Number)x).Pow5;
        [MethodImpl(AggressiveInlining)] public static Number Sqr(this float x) => ((Number)x).Sqr;
        [MethodImpl(AggressiveInlining)] public static Number SineWave(this float x, Number amplitude, Number frequency, Number phase) => ((Number)x).SineWave(amplitude, frequency, phase);
        [MethodImpl(AggressiveInlining)] public static Number StaircaseFloor(this float x, Integer steps) => ((Number)x).StaircaseFloor(steps);
        [MethodImpl(AggressiveInlining)] public static Number StaircaseCeiling(this float x, Integer steps) => ((Number)x).StaircaseCeiling(steps);
        [MethodImpl(AggressiveInlining)] public static Number StaircaseRound(this float x, Integer steps) => ((Number)x).StaircaseRound(steps);
        [MethodImpl(AggressiveInlining)] public static Point2D Spiral(this float t, Number R, Number r, Number numTurns) => ((Number)t).Spiral(R, r, numTurns);
        [MethodImpl(AggressiveInlining)] public static Matrix4x4 Multiply(this Number f, Matrix4x4 value1) => f.Multiply(value1);
        [MethodImpl(AggressiveInlining)] public static Matrix4x4 Multiply(this float f, Matrix4x4 value1) => ((Number)f).Multiply(value1);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Multiply(this Number scalar, Matrix3x2 value1) => scalar.Multiply(value1);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Multiply(this float scalar, Matrix3x2 value1) => ((Number)scalar).Multiply(value1);
        [MethodImpl(AggressiveInlining)] public static Vector2 Multiply(this Number scalar, Vector2 right) => scalar.Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector2 Multiply(this float scalar, Vector2 right) => ((Number)scalar).Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Multiply(this Number scalar, Vector3 right) => scalar.Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Multiply(this float scalar, Vector3 right) => ((Number)scalar).Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector4 Multiply(this Number scalar, Vector4 right) => scalar.Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector4 Multiply(this float scalar, Vector4 right) => ((Number)scalar).Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector8 Multiply(this Number scalar, Vector8 right) => scalar.Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector8 Multiply(this float scalar, Vector8 right) => ((Number)scalar).Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector8 Divide(this Number scalar, Vector8 right) => scalar.Divide(right);
        [MethodImpl(AggressiveInlining)] public static Vector8 Divide(this float scalar, Vector8 right) => ((Number)scalar).Divide(right);
        [MethodImpl(AggressiveInlining)] public static Number Abs(this Number self) => self.Abs;
        [MethodImpl(AggressiveInlining)] public static Number Abs(this float self) => ((Number)self).Abs;
        [MethodImpl(AggressiveInlining)] public static Angle Acos(this Number self) => self.Acos;
        [MethodImpl(AggressiveInlining)] public static Angle Acos(this float self) => ((Number)self).Acos;
        [MethodImpl(AggressiveInlining)] public static Angle Acosh(this Number self) => self.Acosh;
        [MethodImpl(AggressiveInlining)] public static Angle Acosh(this float self) => ((Number)self).Acosh;
        [MethodImpl(AggressiveInlining)] public static Angle Asin(this Number self) => self.Asin;
        [MethodImpl(AggressiveInlining)] public static Angle Asin(this float self) => ((Number)self).Asin;
        [MethodImpl(AggressiveInlining)] public static Angle Asinh(this Number self) => self.Asinh;
        [MethodImpl(AggressiveInlining)] public static Angle Asinh(this float self) => ((Number)self).Asinh;
        [MethodImpl(AggressiveInlining)] public static Angle Atan(this Number self) => self.Atan;
        [MethodImpl(AggressiveInlining)] public static Angle Atan(this float self) => ((Number)self).Atan;
        [MethodImpl(AggressiveInlining)] public static Angle Atan2(this Number self, Number x) => self.Atan2(x);
        [MethodImpl(AggressiveInlining)] public static Angle Atan2(this float self, Number x) => ((Number)self).Atan2(x);
        [MethodImpl(AggressiveInlining)] public static Angle Atanh(this Number self) => self.Atanh;
        [MethodImpl(AggressiveInlining)] public static Angle Atanh(this float self) => ((Number)self).Atanh;
        [MethodImpl(AggressiveInlining)] public static Number BitDecrement(this Number self) => self.BitDecrement;
        [MethodImpl(AggressiveInlining)] public static Number BitDecrement(this float self) => ((Number)self).BitDecrement;
        [MethodImpl(AggressiveInlining)] public static Number BitIncrement(this Number self) => self.BitIncrement;
        [MethodImpl(AggressiveInlining)] public static Number BitIncrement(this float self) => ((Number)self).BitIncrement;
        [MethodImpl(AggressiveInlining)] public static Number Cbrt(this Number self) => self.Cbrt;
        [MethodImpl(AggressiveInlining)] public static Number Cbrt(this float self) => ((Number)self).Cbrt;
        [MethodImpl(AggressiveInlining)] public static Number Ceiling(this Number self) => self.Ceiling;
        [MethodImpl(AggressiveInlining)] public static Number Ceiling(this float self) => ((Number)self).Ceiling;
        [MethodImpl(AggressiveInlining)] public static Number Clamp(this Number self, Number min, Number max) => self.Clamp(min, max);
        [MethodImpl(AggressiveInlining)] public static Number Clamp(this float self, Number min, Number max) => ((Number)self).Clamp(min, max);
        [MethodImpl(AggressiveInlining)] public static Number CopySign(this Number self, Number y) => self.CopySign(y);
        [MethodImpl(AggressiveInlining)] public static Number CopySign(this float self, Number y) => ((Number)self).CopySign(y);
        [MethodImpl(AggressiveInlining)] public static Number Exp(this Number self) => self.Exp;
        [MethodImpl(AggressiveInlining)] public static Number Exp(this float self) => ((Number)self).Exp;
        [MethodImpl(AggressiveInlining)] public static Number Floor(this Number self) => self.Floor;
        [MethodImpl(AggressiveInlining)] public static Number Floor(this float self) => ((Number)self).Floor;
        [MethodImpl(AggressiveInlining)] public static Number FusedMultiplyAdd(this Number self, Number y, Number z) => self.FusedMultiplyAdd(y, z);
        [MethodImpl(AggressiveInlining)] public static Number FusedMultiplyAdd(this float self, Number y, Number z) => ((Number)self).FusedMultiplyAdd(y, z);
        [MethodImpl(AggressiveInlining)] public static Number ILogB(this Number self) => self.ILogB;
        [MethodImpl(AggressiveInlining)] public static Number ILogB(this float self) => ((Number)self).ILogB;
        [MethodImpl(AggressiveInlining)] public static Number IEEERemainder(this Number self, Number y) => self.IEEERemainder(y);
        [MethodImpl(AggressiveInlining)] public static Number IEEERemainder(this float self, Number y) => ((Number)self).IEEERemainder(y);
        [MethodImpl(AggressiveInlining)] public static Number Log(this Number self, Number newBase) => self.Log(newBase);
        [MethodImpl(AggressiveInlining)] public static Number Log(this float self, Number newBase) => ((Number)self).Log(newBase);
        [MethodImpl(AggressiveInlining)] public static Number Log10(this Number self) => self.Log10;
        [MethodImpl(AggressiveInlining)] public static Number Log10(this float self) => ((Number)self).Log10;
        [MethodImpl(AggressiveInlining)] public static Number Log2(this Number self) => self.Log2;
        [MethodImpl(AggressiveInlining)] public static Number Log2(this float self) => ((Number)self).Log2;
        [MethodImpl(AggressiveInlining)] public static Number Min(this Number self, Number other) => self.Min(other);
        [MethodImpl(AggressiveInlining)] public static Number Min(this float self, Number other) => ((Number)self).Min(other);
        [MethodImpl(AggressiveInlining)] public static Number MinMagnitude(this Number self, Number other) => self.MinMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Number MinMagnitude(this float self, Number other) => ((Number)self).MinMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Number Max(this Number self, Number other) => self.Max(other);
        [MethodImpl(AggressiveInlining)] public static Number Max(this float self, Number other) => ((Number)self).Max(other);
        [MethodImpl(AggressiveInlining)] public static Number MaxMagnitude(this Number self, Number other) => self.MaxMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Number MaxMagnitude(this float self, Number other) => ((Number)self).MaxMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Number NaturalLog(this Number self) => self.NaturalLog;
        [MethodImpl(AggressiveInlining)] public static Number NaturalLog(this float self) => ((Number)self).NaturalLog;
        [MethodImpl(AggressiveInlining)] public static Number Pow(this Number self, Number power) => self.Pow(power);
        [MethodImpl(AggressiveInlining)] public static Number Pow(this float self, Number power) => ((Number)self).Pow(power);
        [MethodImpl(AggressiveInlining)] public static Number Reciprocal(this Number self) => self.Reciprocal;
        [MethodImpl(AggressiveInlining)] public static Number Reciprocal(this float self) => ((Number)self).Reciprocal;
        [MethodImpl(AggressiveInlining)] public static Number ReciprocalEstimate(this Number self) => self.ReciprocalEstimate;
        [MethodImpl(AggressiveInlining)] public static Number ReciprocalEstimate(this float self) => ((Number)self).ReciprocalEstimate;
        [MethodImpl(AggressiveInlining)] public static Number ReciprocalSqrtEstimate(this Number self) => self.ReciprocalSqrtEstimate;
        [MethodImpl(AggressiveInlining)] public static Number ReciprocalSqrtEstimate(this float self) => ((Number)self).ReciprocalSqrtEstimate;
        [MethodImpl(AggressiveInlining)] public static Number Round(this Number self, Integer digits) => self.Round(digits);
        [MethodImpl(AggressiveInlining)] public static Number Round(this float self, Integer digits) => ((Number)self).Round(digits);
        [MethodImpl(AggressiveInlining)] public static Number RoundAwayFromZero(this Number self, Integer digits) => self.RoundAwayFromZero(digits);
        [MethodImpl(AggressiveInlining)] public static Number RoundAwayFromZero(this float self, Integer digits) => ((Number)self).RoundAwayFromZero(digits);
        [MethodImpl(AggressiveInlining)] public static Number RoundToZero(this Number self, Integer digits) => self.RoundToZero(digits);
        [MethodImpl(AggressiveInlining)] public static Number RoundToZero(this float self, Integer digits) => ((Number)self).RoundToZero(digits);
        [MethodImpl(AggressiveInlining)] public static Number ScaleB(this Number self, Integer n) => self.ScaleB(n);
        [MethodImpl(AggressiveInlining)] public static Number ScaleB(this float self, Integer n) => ((Number)self).ScaleB(n);
        [MethodImpl(AggressiveInlining)] public static Integer Sign(this Number self) => self.Sign;
        [MethodImpl(AggressiveInlining)] public static Integer Sign(this float self) => ((Number)self).Sign;
        [MethodImpl(AggressiveInlining)] public static Number Sqrt(this Number self) => self.Sqrt;
        [MethodImpl(AggressiveInlining)] public static Number Sqrt(this float self) => ((Number)self).Sqrt;
        [MethodImpl(AggressiveInlining)] public static Number Square(this Number self) => self.Square;
        [MethodImpl(AggressiveInlining)] public static Number Square(this float self) => ((Number)self).Square;
        [MethodImpl(AggressiveInlining)] public static Number Truncate(this Number self) => self.Truncate;
        [MethodImpl(AggressiveInlining)] public static Number Truncate(this float self) => ((Number)self).Truncate;
        [MethodImpl(AggressiveInlining)] public static Number Add(this Number a, Number b) => a.Add(b);
        [MethodImpl(AggressiveInlining)] public static Number Add(this float a, Number b) => ((Number)a).Add(b);
        [MethodImpl(AggressiveInlining)] public static Number Subtract(this Number a, Number b) => a.Subtract(b);
        [MethodImpl(AggressiveInlining)] public static Number Subtract(this float a, Number b) => ((Number)a).Subtract(b);
        [MethodImpl(AggressiveInlining)] public static Number Multiply(this Number a, Number b) => a.Multiply(b);
        [MethodImpl(AggressiveInlining)] public static Number Multiply(this float a, Number b) => ((Number)a).Multiply(b);
        [MethodImpl(AggressiveInlining)] public static Number Divide(this Number a, Number b) => a.Divide(b);
        [MethodImpl(AggressiveInlining)] public static Number Divide(this float a, Number b) => ((Number)a).Divide(b);
        [MethodImpl(AggressiveInlining)] public static Number Negative(this Number n) => n.Negative;
        [MethodImpl(AggressiveInlining)] public static Number Negative(this float n) => ((Number)n).Negative;
        [MethodImpl(AggressiveInlining)] public static Boolean LessThan(this Number a, Number b) => a.LessThan(b);
        [MethodImpl(AggressiveInlining)] public static Boolean LessThan(this float a, Number b) => ((Number)a).LessThan(b);
        [MethodImpl(AggressiveInlining)] public static Boolean LessThanOrEquals(this Number a, Number b) => a.LessThanOrEquals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean LessThanOrEquals(this float a, Number b) => ((Number)a).LessThanOrEquals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean GreaterThan(this Number a, Number b) => a.GreaterThan(b);
        [MethodImpl(AggressiveInlining)] public static Boolean GreaterThan(this float a, Number b) => ((Number)a).GreaterThan(b);
        [MethodImpl(AggressiveInlining)] public static Boolean GreaterThanOrEquals(this Number a, Number b) => a.GreaterThanOrEquals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean GreaterThanOrEquals(this float a, Number b) => ((Number)a).GreaterThanOrEquals(b);
        [MethodImpl(AggressiveInlining)] public static Integer CompareTo(this Number self, Number other) => self.CompareTo(other);
        [MethodImpl(AggressiveInlining)] public static Integer CompareTo(this float self, Number other) => ((Number)self).CompareTo(other);
        [MethodImpl(AggressiveInlining)] public static Angle Multiply(this Number x, Angle a) => x.Multiply(a);
        [MethodImpl(AggressiveInlining)] public static Angle Multiply(this float x, Angle a) => ((Number)x).Multiply(a);
        [MethodImpl(AggressiveInlining)] public static Translation3D TranslationX(this float x) => ((Number)x).TranslationX;
        [MethodImpl(AggressiveInlining)] public static Translation3D TranslationY(this float x) => ((Number)x).TranslationY;
        [MethodImpl(AggressiveInlining)] public static Translation3D TranslationZ(this float x) => ((Number)x).TranslationZ;
        [MethodImpl(AggressiveInlining)] public static Scaling3D UniformScaling3D(this float x) => ((Number)x).UniformScaling3D;
        [MethodImpl(AggressiveInlining)] public static Vector2 Vector2(this float s) => ((Number)s).Vector2;
        [MethodImpl(AggressiveInlining)] public static Vector2 XVector2(this float n) => ((Number)n).XVector2;
        [MethodImpl(AggressiveInlining)] public static Vector2 YVector2(this float n) => ((Number)n).YVector2;
        [MethodImpl(AggressiveInlining)] public static Vector3 Vector3(this float s) => ((Number)s).Vector3;
        [MethodImpl(AggressiveInlining)] public static Vector3 XVector3(this float n) => ((Number)n).XVector3;
        [MethodImpl(AggressiveInlining)] public static Vector3 YVector3(this float n) => ((Number)n).YVector3;
        [MethodImpl(AggressiveInlining)] public static Vector3 ZVector3(this float n) => ((Number)n).ZVector3;
        [MethodImpl(AggressiveInlining)] public static Vector4 Vector4(this float s) => ((Number)s).Vector4;
        [MethodImpl(AggressiveInlining)] public static Vector4 XVector4(this float n) => ((Number)n).XVector4;
        [MethodImpl(AggressiveInlining)] public static Vector4 YVector4(this float n) => ((Number)n).YVector4;
        [MethodImpl(AggressiveInlining)] public static Vector4 ZVector4(this float n) => ((Number)n).ZVector4;
        [MethodImpl(AggressiveInlining)] public static Vector4 WVector4(this float n) => ((Number)n).WVector4;
        [MethodImpl(AggressiveInlining)] public static Vector8 Vector8(this float s) => ((Number)s).Vector8;
        [MethodImpl(AggressiveInlining)] public static Number Barycentric(this float v1, Number v2, Number v3, Vector2 uv) => ((Number)v1).Barycentric(v2, v3, uv);
        [MethodImpl(AggressiveInlining)] public static Number Linear(this float m, Number b, Number x) => ((Number)m).Linear(b, x);
        [MethodImpl(AggressiveInlining)] public static Number Quadratic(this float a, Number b, Number c, Number x) => ((Number)a).Quadratic(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Number Cubic(this float a, Number b, Number c, Number d, Number x) => ((Number)a).Cubic(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Number Quartic(this float a, Number b, Number c, Number d, Number e, Number x) => ((Number)a).Quartic(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Number LinearDerivative(this float m, Number b, Number x) => ((Number)m).LinearDerivative(b, x);
        [MethodImpl(AggressiveInlining)] public static Number LinearSecondDerivative(this float m, Number b, Number x) => ((Number)m).LinearSecondDerivative(b, x);
        [MethodImpl(AggressiveInlining)] public static Number QuadraticDerivative(this float a, Number b, Number c, Number x) => ((Number)a).QuadraticDerivative(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Number QuadraticSecondDerivative(this float a, Number b, Number c, Number x) => ((Number)a).QuadraticSecondDerivative(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Number CubicDerivative(this float a, Number b, Number c, Number d, Number x) => ((Number)a).CubicDerivative(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Number CubicSecondDerivative(this float a, Number b, Number c, Number d, Number x) => ((Number)a).CubicSecondDerivative(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Number QuarticDerivative(this float a, Number b, Number c, Number d, Number e, Number x) => ((Number)a).QuarticDerivative(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Number QuarticSecondDerivative(this float a, Number b, Number c, Number d, Number e, Number x) => ((Number)a).QuarticSecondDerivative(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Number CubicBezier(this float a, Number b, Number c, Number d, Number t) => ((Number)a).CubicBezier(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Number CubicBezierDerivative(this float a, Number b, Number c, Number d, Number t) => ((Number)a).CubicBezierDerivative(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Number CubicBezierSecondDerivative(this float a, Number b, Number c, Number d, Number t) => ((Number)a).CubicBezierSecondDerivative(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Number QuadraticBezier(this float a, Number b, Number c, Number t) => ((Number)a).QuadraticBezier(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Number QuadraticBezierDerivative(this float a, Number b, Number c, Number t) => ((Number)a).QuadraticBezierDerivative(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Number QuadraticBezierSecondDerivative(this float a, Number b, Number c, Number t) => ((Number)a).QuadraticBezierSecondDerivative(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Number Hermite(this float p0, Number p1, Number m0, Number m1, Number t) => ((Number)p0).Hermite(p1, m0, m1, t);
        [MethodImpl(AggressiveInlining)] public static Number HermiteDerivative(this float p0, Number p1, Number m0, Number m1, Number t) => ((Number)p0).HermiteDerivative(p1, m0, m1, t);
        [MethodImpl(AggressiveInlining)] public static Number CatmullRom(this float p0, Number p1, Number p2, Number p3, Number t) => ((Number)p0).CatmullRom(p1, p2, p3, t);
        [MethodImpl(AggressiveInlining)] public static Number CatmullRomDerivative(this float p0, Number p1, Number p2, Number p3, Number t) => ((Number)p0).CatmullRomDerivative(p1, p2, p3, t);
        [MethodImpl(AggressiveInlining)] public static Number SmoothStep(this float x) => ((Number)x).SmoothStep;
        [MethodImpl(AggressiveInlining)] public static Number SmootherStep(this float x) => ((Number)x).SmootherStep;
        [MethodImpl(AggressiveInlining)] public static Number Reduce(this float v, Number initial, System.Func<Number, Number, Number> f) => ((Number)v).Reduce(initial, f);
        [MethodImpl(AggressiveInlining)] public static Number MinComponent(this float x) => ((Number)x).MinComponent;
        [MethodImpl(AggressiveInlining)] public static Number MaxComponent(this float x) => ((Number)x).MaxComponent;
        [MethodImpl(AggressiveInlining)] public static Number SumComponents(this float v) => ((Number)v).SumComponents;
        [MethodImpl(AggressiveInlining)] public static Number SumSqrComponents(this float v) => ((Number)v).SumSqrComponents;
        [MethodImpl(AggressiveInlining)] public static Number AvgComponent(this float v) => ((Number)v).AvgComponent;
        [MethodImpl(AggressiveInlining)] public static Number Magnitude(this float v) => ((Number)v).Magnitude;
        [MethodImpl(AggressiveInlining)] public static Number MagnitudeSquared(this float v) => ((Number)v).MagnitudeSquared;
        [MethodImpl(AggressiveInlining)] public static Number ReciprocalSquareRootEstimate(this float self) => ((Number)self).ReciprocalSquareRootEstimate;
        [MethodImpl(AggressiveInlining)] public static System.Collections.Generic.IReadOnlyList<Number> Sample(this float a, Number b, Integer n) => ((Number)a).Sample(b, n);
        [MethodImpl(AggressiveInlining)] public static Number Half(this float x) => ((Number)x).Half;
        [MethodImpl(AggressiveInlining)] public static Number Quarter(this float x) => ((Number)x).Quarter;
        [MethodImpl(AggressiveInlining)] public static Number Eight(this float x) => ((Number)x).Eight;
        [MethodImpl(AggressiveInlining)] public static Number Sixteenth(this float x) => ((Number)x).Sixteenth;
        [MethodImpl(AggressiveInlining)] public static Number Tenth(this float x) => ((Number)x).Tenth;
        [MethodImpl(AggressiveInlining)] public static Number Twice(this float x) => ((Number)x).Twice;
        [MethodImpl(AggressiveInlining)] public static Number Hundred(this float x) => ((Number)x).Hundred;
        [MethodImpl(AggressiveInlining)] public static Number Thousand(this float x) => ((Number)x).Thousand;
        [MethodImpl(AggressiveInlining)] public static Number Million(this float x) => ((Number)x).Million;
        [MethodImpl(AggressiveInlining)] public static Number Billion(this float x) => ((Number)x).Billion;
        [MethodImpl(AggressiveInlining)] public static Number Hundredth(this float x) => ((Number)x).Hundredth;
        [MethodImpl(AggressiveInlining)] public static Number Thousandth(this float x) => ((Number)x).Thousandth;
        [MethodImpl(AggressiveInlining)] public static Number Millionth(this float x) => ((Number)x).Millionth;
        [MethodImpl(AggressiveInlining)] public static Number Billionth(this float x) => ((Number)x).Billionth;
        [MethodImpl(AggressiveInlining)] public static Number At(this float xs, Integer n) => ((Number)xs).At(n);
        [MethodImpl(AggressiveInlining)] public static Number MapComponents(this float x, System.Func<Number, Number> f) => ((Number)x).MapComponents(f);
        [MethodImpl(AggressiveInlining)] public static Number ZipComponents(this float a, Number b, System.Func<Number, Number, Number> f) => ((Number)a).ZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Number ZipComponents(this float a, Number b, Number c, System.Func<Number, Number, Number, Number> f) => ((Number)a).ZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllZipComponents(this float a, Number b, System.Func<Number, Number, Boolean> f) => ((Number)a).AllZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllZipComponents(this float a, Number b, Number c, System.Func<Number, Number, Number, Boolean> f) => ((Number)a).AllZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyZipComponents(this float a, Number b, System.Func<Number, Number, Boolean> f) => ((Number)a).AnyZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyZipComponents(this float a, Number b, Number c, System.Func<Number, Number, Number, Boolean> f) => ((Number)a).AnyZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllComponents(this float x, System.Func<Number, Boolean> predicate) => ((Number)x).AllComponents(predicate);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyComponent(this float x, System.Func<Number, Boolean> predicate) => ((Number)x).AnyComponent(predicate);
        [MethodImpl(AggressiveInlining)] public static Number Lesser(this float a, Number b) => ((Number)a).Lesser(b);
        [MethodImpl(AggressiveInlining)] public static Number Greater(this float a, Number b) => ((Number)a).Greater(b);
    }
}
