// Autogenerated file: DO NOT EDIT
// Created on 2025-06-03 11:05:01 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Plato
{
    public static partial class Extensions
    {
        [MethodImpl(AggressiveInlining)] public static Bounds2D Bounds(this System.Collections.Generic.IReadOnlyList<Point2D> xs) => xs.Reduce(Plato.Bounds2D.Empty, (a, b)  => a.Include(b));
[MethodImpl(AggressiveInlining)] public static Bounds3D Bounds(this System.Collections.Generic.IReadOnlyList<Point3D> xs) => xs.Reduce(Plato.Bounds3D.Empty, (a, b)  => a.Include(b));
[MethodImpl(AggressiveInlining)] public static System.Collections.Generic.IReadOnlyList<Line2D> Lines(this System.Collections.Generic.IReadOnlyList<Line2D> xs) => xs;
[MethodImpl(AggressiveInlining)] public static System.Collections.Generic.IReadOnlyList<Line3D> Lines(this System.Collections.Generic.IReadOnlyList<Line3D> xs) => xs;
[MethodImpl(AggressiveInlining)] public static System.Collections.Generic.IReadOnlyList<Line2D> Lines(this System.Collections.Generic.IReadOnlyList<Triangle2D> xs) => xs.FlatMap((x)  => x.Lines);
[MethodImpl(AggressiveInlining)] public static System.Collections.Generic.IReadOnlyList<Line3D> Lines(this System.Collections.Generic.IReadOnlyList<Triangle3D> xs) => xs.FlatMap((x)  => x.Lines);
[MethodImpl(AggressiveInlining)] public static System.Collections.Generic.IReadOnlyList<Line2D> Lines(this System.Collections.Generic.IReadOnlyList<Quad2D> xs) => xs.FlatMap((x)  => x.Lines);
[MethodImpl(AggressiveInlining)] public static System.Collections.Generic.IReadOnlyList<Line3D> Lines(this System.Collections.Generic.IReadOnlyList<Quad3D> xs) => xs.FlatMap((x)  => x.Lines);
[MethodImpl(AggressiveInlining)] public static System.Collections.Generic.IReadOnlyList<Triangle2D> Triangles(this System.Collections.Generic.IReadOnlyList<Triangle2D> xs) => xs;
[MethodImpl(AggressiveInlining)] public static System.Collections.Generic.IReadOnlyList<Triangle3D> Triangles(this System.Collections.Generic.IReadOnlyList<Triangle3D> xs) => xs;
[MethodImpl(AggressiveInlining)] public static System.Collections.Generic.IReadOnlyList<Triangle2D> Triangles(this System.Collections.Generic.IReadOnlyList<Quad2D> xs) => xs.FlatMap((x)  => x.Triangles);
[MethodImpl(AggressiveInlining)] public static System.Collections.Generic.IReadOnlyList<Triangle3D> Triangles(this System.Collections.Generic.IReadOnlyList<Quad3D> xs) => xs.FlatMap((x)  => x.Triangles);
[MethodImpl(AggressiveInlining)] public static Ara3D.Collections.IReadOnlyList2D<Integer4> AllQuadFaceIndices<_T0>(this Ara3D.Collections.IReadOnlyList2D<_T0> xs, Boolean closedX, Boolean closedY) => xs.NumColumns.AllQuadFaceIndices(xs.NumRows, closedX, closedY);
}
}
