<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PropertyDescriptors\**" />
    <EmbeddedResource Remove="PropertyDescriptors\**" />
    <None Remove="PropertyDescriptors\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="$(Ara3DCoverletCollectorVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(Ara3DMicrosoftNetTestSdkVersion)" />
    <PackageReference Include="NUnit" Version="$(Ara3DNUnitVersion)" />
    <PackageReference Include="NUnit.Analyzers" Version="$(Ara3DNUnitAnalyzersVersion)" />
    <PackageReference Include="NUnit3TestAdapter" Version="$(Ara3DNUnit3TestAdapterVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ara3D.Memory\Ara3D.Memory.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.PropKit\Ara3D.PropKit.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.IO.VIM\Ara3D.IO.VIM.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.Logging\Ara3D.Logging.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.Utils\Ara3D.Utils.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.IO.BFAST\Ara3D.IO.BFAST.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.Utils\Ara3D.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
