// Autogenerated file: DO NOT EDIT
// Created on 2025-06-04 10:07:55 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct QuadGrid3D: IQuadGrid3D<QuadGrid3D>
    {
        // Fields
        [DataMember] public readonly IReadOnlyList2D<Point3D> Grid;
        [DataMember] public readonly Boolean ClosedX;
        [DataMember] public readonly Boolean ClosedY;

        // With functions 
        [MethodImpl(AggressiveInlining)] public QuadGrid3D WithGrid(IReadOnlyList2D<Point3D> grid) => new QuadGrid3D(grid, ClosedX, ClosedY);
        [MethodImpl(AggressiveInlining)] public QuadGrid3D WithClosedX(Boolean closedX) => new QuadGrid3D(Grid, closedX, ClosedY);
        [MethodImpl(AggressiveInlining)] public QuadGrid3D WithClosedY(Boolean closedY) => new QuadGrid3D(Grid, ClosedX, closedY);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public QuadGrid3D(IReadOnlyList2D<Point3D> grid, Boolean closedX, Boolean closedY) { Grid = grid; ClosedX = closedX; ClosedY = closedY; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static QuadGrid3D Create(IReadOnlyList2D<Point3D> grid, Boolean closedX, Boolean closedY) => new QuadGrid3D(grid, closedX, closedY);

        // Static default implementation
        public static readonly QuadGrid3D Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (IReadOnlyList2D<Point3D>, Boolean, Boolean)(QuadGrid3D self) => (self.Grid, self.ClosedX, self.ClosedY);
        [MethodImpl(AggressiveInlining)] public static implicit operator QuadGrid3D((IReadOnlyList2D<Point3D>, Boolean, Boolean) value) => new QuadGrid3D(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out IReadOnlyList2D<Point3D> grid, out Boolean closedX, out Boolean closedY) { grid = Grid; closedX = ClosedX; closedY = ClosedY;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(QuadGrid3D other) => Grid.Equals(other.Grid) && ClosedX.Equals(other.ClosedX) && ClosedY.Equals(other.ClosedY);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(QuadGrid3D other) => !Grid.Equals(other.Grid) && ClosedX.Equals(other.ClosedX) && ClosedY.Equals(other.ClosedY);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is QuadGrid3D other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Grid, ClosedX, ClosedY);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Grid\" = {Grid}, \"ClosedX\" = {ClosedX}, \"ClosedY\" = {ClosedY} }}";

        // Explicit implementation of interfaces by forwarding properties to fields
        Boolean IQuadGrid3D<QuadGrid3D>.ClosedX { [MethodImpl(AggressiveInlining)] get => ClosedX; }
        Boolean IQuadGrid3D<QuadGrid3D>.ClosedY { [MethodImpl(AggressiveInlining)] get => ClosedY; }

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public QuadGrid3D Deform(System.Func<Point3D, Point3D> f) => new QuadGrid3D(this.PointGrid.Map(f), this.ClosedX, this.ClosedY);
public Integer NumColumns { [MethodImpl(AggressiveInlining)] get  => this.Grid.NumColumns; } 
public Integer NumRows { [MethodImpl(AggressiveInlining)] get  => this.Grid.NumRows; } 
public IReadOnlyList<Point3D> Points { [MethodImpl(AggressiveInlining)] get  => this.Grid; } 
public IReadOnlyList<Integer4> FaceIndices { [MethodImpl(AggressiveInlining)] get  => this.Grid.AllQuadFaceIndices(this.ClosedX, this.ClosedY); } 
public IReadOnlyList<Integer> Indices { [MethodImpl(AggressiveInlining)] get  => this.FaceIndices.FlatMap((fi)  => fi.Components); } 
public IReadOnlyList<Quad3D> Faces { [MethodImpl(AggressiveInlining)] get  => this.Quads; } 
public IReadOnlyList<Quad3D> Quads { [MethodImpl(AggressiveInlining)] get {
            var _var127 = this;
            return this.FaceIndices.Map((f)  => _var127.Quad(f));
        }
         } 
public Integer NumPrimitives { [MethodImpl(AggressiveInlining)] get  => this.Indices.Count.Divide(this.PrimitiveSize); } 
[MethodImpl(AggressiveInlining)] public Point3D Point(Integer index) => this.Points[index];
[MethodImpl(AggressiveInlining)] public Triangle3D Triangle(Integer3 f) => (this.Point(f.A), this.Point(f.B), this.Point(f.C));
[MethodImpl(AggressiveInlining)] public Quad3D Quad(Integer4 f) => (this.Point(f.A), this.Point(f.B), this.Point(f.C), this.Point(f.D));
public Bounds3D Bounds { [MethodImpl(AggressiveInlining)] get  => this.Points.Bounds(); } 
[MethodImpl(AggressiveInlining)] public QuadGrid3D Deform<_T0>(_T0 t) where _T0 : ITransform3D{
            var _var128 = t;
            return this.Deform((v)  => v.Vector3.Transform(_var128.Matrix));
        }

[MethodImpl(AggressiveInlining)] public QuadGrid3D Scale(Vector3 v){
            var _var129 = v;
            return this.Deform((p)  => p.Vector3.Multiply(_var129));
        }

[MethodImpl(AggressiveInlining)] public QuadGrid3D Scale(Number s) => this.Scale((s, s, s));
[MethodImpl(AggressiveInlining)] public QuadGrid3D ScaleX(Number s) => this.Scale((s, ((Integer)1), ((Integer)1)));
[MethodImpl(AggressiveInlining)] public QuadGrid3D ScaleY(Number s) => this.Scale((((Integer)1), s, ((Integer)1)));
[MethodImpl(AggressiveInlining)] public QuadGrid3D ScaleZ(Number s) => this.Scale((((Integer)1), ((Integer)1), s));
[MethodImpl(AggressiveInlining)] public QuadGrid3D Rotate(Quaternion q){
            var _var130 = q;
            return this.Deform((v)  => _var130.Transform(v));
        }

[MethodImpl(AggressiveInlining)] public QuadGrid3D RotateX(Angle a) => this.Rotate(a.RotateX);
[MethodImpl(AggressiveInlining)] public QuadGrid3D RotateY(Angle a) => this.Rotate(a.RotateY);
[MethodImpl(AggressiveInlining)] public QuadGrid3D RotateZ(Angle a) => this.Rotate(a.RotateZ);
[MethodImpl(AggressiveInlining)] public QuadGrid3D Translate(Vector3 v){
            var _var131 = v;
            return this.Deform((p)  => p.Add(_var131));
        }

[MethodImpl(AggressiveInlining)] public QuadGrid3D TranslateX(Number s) => this.Translate(s.XVector3);
[MethodImpl(AggressiveInlining)] public QuadGrid3D TranslateY(Number s) => this.Translate(s.YVector3);
[MethodImpl(AggressiveInlining)] public QuadGrid3D TranslateZ(Number s) => this.Translate(s.ZVector3);
public Integer PrimitiveSize { [MethodImpl(AggressiveInlining)] get  => ((Integer)4); } 

        // Unimplemented interface functions
        public IReadOnlyList<Quad3D> Primitives => throw new NotImplementedException();
public IReadOnlyList2D<Point3D> PointGrid => throw new NotImplementedException();
}
    // Extension methods for the type
    public static partial class Extensions
    {
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Quad3D> Primitives(this QuadGrid3D x) => x.Primitives;
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList2D<Point3D> PointGrid(this QuadGrid3D x) => x.PointGrid;
    }
}
