// Autogenerated file: DO NOT EDIT
// Created on 2025-06-04 10:07:55 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct QuadArray2D: IQuadArray2D<QuadArray2D>
    {
        // Fields
        [DataMember] public readonly IReadOnlyList<Quad2D> Quads;

        // With functions 
        [MethodImpl(AggressiveInlining)] public QuadArray2D WithQuads(IReadOnlyList<Quad2D> quads) => new QuadArray2D(quads);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public QuadArray2D(IReadOnlyList<Quad2D> quads) { Quads = quads; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static QuadArray2D Create(IReadOnlyList<Quad2D> quads) => new QuadArray2D(quads);

        // Static default implementation
        public static readonly QuadArray2D Default = default;

        // Implicit converters to/from single field

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(QuadArray2D other) => Quads.Equals(other.Quads);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(QuadArray2D other) => !Quads.Equals(other.Quads);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is QuadArray2D other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Quads);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Quads\" = {Quads} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public QuadArray2D Deform(System.Func<Point2D, Point2D> f){
            var _var120 = f;
            return new QuadArray2D(this.Quads.Map((q)  => q.Deform(_var120)));
        }

public IReadOnlyList<Point2D> Points { [MethodImpl(AggressiveInlining)] get  => this.Quads.FlatMap((x)  => x.Points); } 
public IReadOnlyList<Line2D> Lines { [MethodImpl(AggressiveInlining)] get  => this.Quads.FlatMap((x)  => x.Lines); } 
public IReadOnlyList<Triangle2D> Triangles { [MethodImpl(AggressiveInlining)] get  => this.Quads.FlatMap((x)  => x.Triangles); } 
public Integer PrimitiveSize { [MethodImpl(AggressiveInlining)] get  => ((Integer)4); } 

        // Unimplemented interface functions
        public Integer NumPrimitives => throw new NotImplementedException();
public IReadOnlyList<Quad2D> Primitives => throw new NotImplementedException();
}
    // Extension methods for the type
    public static partial class Extensions
    {
        [MethodImpl(AggressiveInlining)] public static Integer NumPrimitives(this QuadArray2D x) => x.NumPrimitives;
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Quad2D> Primitives(this QuadArray2D x) => x.Primitives;
    }
}
