<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="$(Ara3DNewtonsoftJsonVersion)" />
    <PackageReference Include="System.Resources.Extensions" Version="$(Ara3DSystemResourcesExtensionsVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ara3D.Bowerbird\Ara3D.Bowerbird.csproj" />
  </ItemGroup>

</Project>