    Console.WriteLine("solid pyramid");
    Console.WriteLine("  facet normal 0 0 0");
    Console.WriteLine("    outer loop");
    Console.WriteLine("      vertex -0.5 -0.5 0");
    Console.WriteLine("      vertex 0.5 -0.5 0");
    Console.WriteLine("      vertex 0 0 1");
    Console.WriteLine("    endloop");
    Console.WriteLine("  endfacet");
    Console.WriteLine("  facet normal 0 0 0");
    Console.WriteLine("    outer loop");
    Console.WriteLine("      vertex 0.5 -0.5 0");
    Console.WriteLine("      vertex 0.5 0.5 0");
    Console.WriteLine("      vertex 0 0 1");
    Console.WriteLine("    endloop");
    Console.WriteLine("  endfacet");
    Console.WriteLine("  facet normal 0 0 0");
    Console.WriteLine("    outer loop");
    Console.WriteLine("      vertex 0.5 0.5 0");
    Console.WriteLine("      vertex -0.5 0.5 0");
    Console.WriteLine("      vertex 0 0 1");
    Console.WriteLine("    endloop");
    Console.WriteLine("  endfacet");
    Console.WriteLine("  facet normal 0 0 0");
    Console.WriteLine("    outer loop");
    Console.WriteLine("      vertex -0.5 0.5 0");
    Console.WriteLine("      vertex -0.5 -0.5 0");
    Console.WriteLine("      vertex 0 0 1");
    Console.WriteLine("    endloop");
    Console.WriteLine("  endfacet");
    Console.WriteLine("endsolid pyramid");