<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Ara3D.IfcMeshingComparison</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);NUnit2021</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="$(Ara3DCoverletCollectorVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(Ara3DMicrosoftNetTestSdkVersion)" />
    <PackageReference Include="NUnit" Version="$(Ara3DNUnitVersion)" />
    <PackageReference Include="NUnit.Analyzers" Version="$(Ara3DNUnitAnalyzersVersion)" />
    <PackageReference Include="NUnit3TestAdapter" Version="$(Ara3DNUnit3TestAdapterVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ext\Ara3D.IfcLoader\Ara3D.IfcLoader.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.Geometry\Ara3D.Geometry.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.IO.StepParser\Ara3D.IO.StepParser.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.Memory\Ara3D.Memory.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.Models\Ara3D.Models.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.Utils\Ara3D.Utils.csproj" />
    <ProjectReference Include="..\..\wip\Ara3D.Ifc.Mesher\Ara3D.Ifc.Mesher.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <Using Include="Ara3D.IfcTypes.Ifc4" />
  </ItemGroup>

</Project>
