<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
  	<UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Description>WPF and WinForms helpers for Ara 3D SDK desktop applications.</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ara3D.Utils.Wpf.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ara3D.Geometry\Ara3D.Geometry.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.Utils\Ara3D.Utils.csproj" />
  </ItemGroup>

</Project>
