<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Description>BIM Open Schema model and IO packages for Ara 3D SDK applications.</Description>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <PackageType>Dependency</PackageType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ara3D.BimOpenSchema\Ara3D.BimOpenSchema.csproj" />
    <ProjectReference Include="..\Ara3D.BimOpenSchema.IO\Ara3D.BimOpenSchema.IO.csproj" />
  </ItemGroup>
</Project>
