<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="$(Ara3DMicrosoftCodeAnalysisCSharpVersion)" />
    <PackageReference Include="Microsoft.DiaSymReader.Native" Version="$(Ara3DMicrosoftDiaSymReaderNativeVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ara3D.Logging\Ara3D.Logging.csproj" />
  </ItemGroup>
</Project>